NAME = libftprintf.a

OBJ_FILES = ft_printf.o

HEADER_FILES = includes/ft_printf.h

all:
	$(CC) -g main.c srcs/ft_printf.c srcs/helperfunctions.c libft/libft.a
	./a.out

$(NAME):
	$(CC)

clean:

fclean:

re:

.PHONY:
